/*
 * Swagger CrowdSec
 * CrowdSec local API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@crowdsec.net
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Decision;
import com.konfigthis.client.model.Event;
import com.konfigthis.client.model.MetaInner;
import com.konfigthis.client.model.Source;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Alert
 */
public class AlertTest {
    private final Alert model = new Alert();

    /**
     * Model tests for Alert
     */
    @Test
    public void testAlert() {
        // TODO: test Alert
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'machineId'
     */
    @Test
    public void machineIdTest() {
        // TODO: test machineId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'scenario'
     */
    @Test
    public void scenarioTest() {
        // TODO: test scenario
    }

    /**
     * Test the property 'scenarioHash'
     */
    @Test
    public void scenarioHashTest() {
        // TODO: test scenarioHash
    }

    /**
     * Test the property 'scenarioVersion'
     */
    @Test
    public void scenarioVersionTest() {
        // TODO: test scenarioVersion
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'eventsCount'
     */
    @Test
    public void eventsCountTest() {
        // TODO: test eventsCount
    }

    /**
     * Test the property 'startAt'
     */
    @Test
    public void startAtTest() {
        // TODO: test startAt
    }

    /**
     * Test the property 'stopAt'
     */
    @Test
    public void stopAtTest() {
        // TODO: test stopAt
    }

    /**
     * Test the property 'capacity'
     */
    @Test
    public void capacityTest() {
        // TODO: test capacity
    }

    /**
     * Test the property 'leakspeed'
     */
    @Test
    public void leakspeedTest() {
        // TODO: test leakspeed
    }

    /**
     * Test the property 'simulated'
     */
    @Test
    public void simulatedTest() {
        // TODO: test simulated
    }

    /**
     * Test the property 'events'
     */
    @Test
    public void eventsTest() {
        // TODO: test events
    }

    /**
     * Test the property 'remediation'
     */
    @Test
    public void remediationTest() {
        // TODO: test remediation
    }

    /**
     * Test the property 'decisions'
     */
    @Test
    public void decisionsTest() {
        // TODO: test decisions
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

}
