/*
 * Swagger CrowdSec
 * CrowdSec local API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@crowdsec.net
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MetricsBouncerInfo
 */
public class MetricsBouncerInfoTest {
    private final MetricsBouncerInfo model = new MetricsBouncerInfo();

    /**
     * Model tests for MetricsBouncerInfo
     */
    @Test
    public void testMetricsBouncerInfo() {
        // TODO: test MetricsBouncerInfo
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'customName'
     */
    @Test
    public void customNameTest() {
        // TODO: test customName
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'lastPull'
     */
    @Test
    public void lastPullTest() {
        // TODO: test lastPull
    }

}
