/*
 * Swagger CrowdSec
 * CrowdSec local API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@crowdsec.net
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WatcherAuthRequest
 */
public class WatcherAuthRequestTest {
    private final WatcherAuthRequest model = new WatcherAuthRequest();

    /**
     * Model tests for WatcherAuthRequest
     */
    @Test
    public void testWatcherAuthRequest() {
        // TODO: test WatcherAuthRequest
    }

    /**
     * Test the property 'machineId'
     */
    @Test
    public void machineIdTest() {
        // TODO: test machineId
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'scenarios'
     */
    @Test
    public void scenariosTest() {
        // TODO: test scenarios
    }

}
