/*
 * Swagger CrowdSec
 * CrowdSec local API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@crowdsec.net
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MetricsAgentInfo;
import com.konfigthis.client.model.MetricsBouncerInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Metrics
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class Metrics {
  public static final String SERIALIZED_NAME_APIL_VERSION = "apil_version";
  @SerializedName(SERIALIZED_NAME_APIL_VERSION)
  private String apilVersion;

  public static final String SERIALIZED_NAME_BOUNCERS = "bouncers";
  @SerializedName(SERIALIZED_NAME_BOUNCERS)
  private List<MetricsBouncerInfo> bouncers = new ArrayList<>();

  public static final String SERIALIZED_NAME_MACHINES = "machines";
  @SerializedName(SERIALIZED_NAME_MACHINES)
  private List<MetricsAgentInfo> machines = new ArrayList<>();

  public Metrics() {
  }

  public Metrics apilVersion(String apilVersion) {
    
    
    
    
    this.apilVersion = apilVersion;
    return this;
  }

   /**
   * the local version of crowdsec/apil
   * @return apilVersion
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "the local version of crowdsec/apil")

  public String getApilVersion() {
    return apilVersion;
  }


  public void setApilVersion(String apilVersion) {
    
    
    
    this.apilVersion = apilVersion;
  }


  public Metrics bouncers(List<MetricsBouncerInfo> bouncers) {
    
    
    
    
    this.bouncers = bouncers;
    return this;
  }

  public Metrics addBouncersItem(MetricsBouncerInfo bouncersItem) {
    this.bouncers.add(bouncersItem);
    return this;
  }

   /**
   * Get bouncers
   * @return bouncers
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<MetricsBouncerInfo> getBouncers() {
    return bouncers;
  }


  public void setBouncers(List<MetricsBouncerInfo> bouncers) {
    
    
    
    this.bouncers = bouncers;
  }


  public Metrics machines(List<MetricsAgentInfo> machines) {
    
    
    
    
    this.machines = machines;
    return this;
  }

  public Metrics addMachinesItem(MetricsAgentInfo machinesItem) {
    this.machines.add(machinesItem);
    return this;
  }

   /**
   * Get machines
   * @return machines
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<MetricsAgentInfo> getMachines() {
    return machines;
  }


  public void setMachines(List<MetricsAgentInfo> machines) {
    
    
    
    this.machines = machines;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Metrics instance itself
   */
  public Metrics putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Metrics metrics = (Metrics) o;
    return Objects.equals(this.apilVersion, metrics.apilVersion) &&
        Objects.equals(this.bouncers, metrics.bouncers) &&
        Objects.equals(this.machines, metrics.machines)&&
        Objects.equals(this.additionalProperties, metrics.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apilVersion, bouncers, machines, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Metrics {\n");
    sb.append("    apilVersion: ").append(toIndentedString(apilVersion)).append("\n");
    sb.append("    bouncers: ").append(toIndentedString(bouncers)).append("\n");
    sb.append("    machines: ").append(toIndentedString(machines)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("apil_version");
    openapiFields.add("bouncers");
    openapiFields.add("machines");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("apil_version");
    openapiRequiredFields.add("bouncers");
    openapiRequiredFields.add("machines");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Metrics
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Metrics.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Metrics is not found in the empty JSON string", Metrics.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Metrics.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("apil_version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `apil_version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("apil_version").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("bouncers").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `bouncers` to be an array in the JSON string but got `%s`", jsonObj.get("bouncers").toString()));
      }

      JsonArray jsonArraybouncers = jsonObj.getAsJsonArray("bouncers");
      // validate the required field `bouncers` (array)
      for (int i = 0; i < jsonArraybouncers.size(); i++) {
        MetricsBouncerInfo.validateJsonObject(jsonArraybouncers.get(i).getAsJsonObject());
      };
      // ensure the json data is an array
      if (!jsonObj.get("machines").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `machines` to be an array in the JSON string but got `%s`", jsonObj.get("machines").toString()));
      }

      JsonArray jsonArraymachines = jsonObj.getAsJsonArray("machines");
      // validate the required field `machines` (array)
      for (int i = 0; i < jsonArraymachines.size(); i++) {
        MetricsAgentInfo.validateJsonObject(jsonArraymachines.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Metrics.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Metrics' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Metrics> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Metrics.class));

       return (TypeAdapter<T>) new TypeAdapter<Metrics>() {
           @Override
           public void write(JsonWriter out, Metrics value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Metrics read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             Metrics instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Metrics given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Metrics
  * @throws IOException if the JSON string is invalid with respect to Metrics
  */
  public static Metrics fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Metrics.class);
  }

 /**
  * Convert an instance of Metrics to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

